author: JoshuaKGoldberg
description: Runs OctoGuide as a GitHub Action. 🗺️
inputs:
  config:
    description: Which config to use, as 'recommended' (default) or 'strict'.
  github-token:
    description: GitHub token (PAT) with repo and workflow permissions.
name: OctoGuide Action
runs:
  main: dist/index.js
  using: node20
